### ISSUE TITLE
Problem adding Venue Area when using character with accent in the name

### ISSUE THREAD

**Issue by galapas** [quadshot/opentickets-community#10]
Hi,

When I try to add an Event Area in the Venue admin page, the Area is not being added if I type the Area Name with an accent, i don't tested with another latin characters or special chars...

**Comment by loushou** [comment]
Hey @galapas ,

Thanks for pointing this out. Turns out that I used the wrong JS encoding function when doing the ajax (because it is customized for other reasons). I have repaired this, and is fixed in the release I just made, 1.11.2. Let me know how this works for you.

Loushou

**Comment by galapas** [comment]
Thank You @loushou , it works now with portuguese names
