### ISSUE TITLE
WooCommerce Calendar Missing

### ISSUE THREAD

**Issue by dimu505** [quadshot/opentickets-community#20]
I'm unable to display a calendar on the front end.  It looks like woo commerce no longer offers that option.  Please advise.  thanks

**Comment by michaelcremean** [comment]
The Calendar isn't from WooCommerce, it is a template chosen from WordPress.  

You should be able to make a page, and then in the 'Template' box choose 'OpenTickets Calendar'.

**Comment by dimu505** [comment]
Thanks Michael, 

that was exactly what I needed!  Is there a widget or bb code I can use to put the calendar on my home page?
