### ISSUE TITLE
Problem after install of 1.10.24

### ISSUE THREAD

**Issue by IntruderHT** [quadshot/opentickets-community#7]
After updating otc from 1.10.23 to 1.10.24 Text and Picture are not visible on mainsite anymore.

Main-Site with deactivated 1.10.24. The same as with active 1.10.23
![unbenannt-4](https://cloud.githubusercontent.com/assets/12294354/8128645/58d4cd16-1101-11e5-8695-9592f93058aa.png)

Main-Site with active 1.10.24
![unbenannt-2](https://cloud.githubusercontent.com/assets/12294354/8128669/820ed4ec-1101-11e5-89a6-23bd581f001f.png)

I am using the Theme AccessPressLite. But i don't think that is a problem with the Theme. All other Standard-Themes showing the same problem.

Any ideas?

Greets
Intruder

**Comment by IntruderHT** [comment]
OK. Hope this little hint will help you. The change of the file inc\venues\post-type.class.php brought the site back to normal look.
Greets
Intruder

**Comment by loushou** [comment]
Hey @IntruderHT ,

Thanks for reporting this. I will look into it straight away. I will post here once I have an update.

Loushou

**Comment by loushou** [comment]
Hey @IntruderHT,

This has been resolved. Your hint did help track it down, so thanks for that. Sorry for the down time, and thanks for reporting the bug.

Loushou

**Comment by IntruderHT** [comment]
Great work. Thanks
