### ISSUE TITLE
Not possible to create new event after update to 1.11

### ISSUE THREAD

**Issue by IntruderHT** [quadshot/opentickets-community#8]
Hi all together

after updating to the actual version 1.11 there is no possibility to create new event.
I can add a new event by clicking in the Event Date Time settings on "New Event", can perform all settings, but if i want to publish the event by clicking on the "Publish" button, i will get a blank site.
Testet several settings in the new Option-Field Event Titles, but i get allways the same result.
I dont know if the problem came from the file "Tools.js". It is only speculation.
I hope you can find the problem soon.

Greetings from Germany
Holger
IntruderHT

**Comment by Pixeltramp** [comment]
Seconding this issue! 

If a date / venue is chosen, I get the error `Fatal error: Cannot use object of type stdClass as array in /home/xxxxxxxxxxxxx/public_html/wp-content/plugins/opentickets-community-edition/inc/core/post-type.class.php on line 1245"`

The event saves, but no date or venue attachment is set.

**Comment by galapas** [comment]
Hi,

I'm also updated to version 1.11 and the same problem related by IntruderHT when trying to publish an event, only a blank page appears and the event is not published/updated if "New Event" is configured...

**Comment by loushou** [comment]
Hey @galapas @Pixeltramp ,

Sorry for the delay. A release that fixes this was released earlier today to WordPress.org. I just updated the releases here too. Let me know if this resolves it for you. Seems to do the trick for various others.

Loushou

**Comment by IntruderHT** [comment]
Hey Loushou,

looks great and all changed back to normal.

IntruderHT
